import streamlit as st
import json
import pandas as pd
import time
import os
import plotly.express as px

# Configuration of the page
st.set_page_config(
    page_title="Intrusion Detection Dashboard",
    page_icon="🛡️",
    layout="wide",
)

st.title("🛡️ Real-time Intrusion Detection Dashboard")
st.markdown("### Distributed Multi-Agent System (SPADE + Kafka + River)")

# Path to the metrics file generated by SupervisorAgent
METRICS_FILE = "data/metrics.json"

def load_metrics():
    if os.path.exists(METRICS_FILE):
        try:
            with open(METRICS_FILE, "r") as f:
                return json.load(f)
        except Exception:
            return None
    return None

# Sidebar for controls
st.sidebar.header("Configuration")
refresh_rate = st.sidebar.slider("Refresh rate (seconds)", 1, 10, 2)

# Main content
data = load_metrics()

if data:
    metrics = data.get("metrics", {})
    drift_count = data.get("drift_count", 0)
    
    # Top row: Key Metrics
    col1, col2, col3, col4 = st.columns(4)
    col1.metric("Accuracy", f"{metrics.get('Accuracy', 0):.4f}")
    col2.metric("F1-Score", f"{metrics.get('F1', 0):.4f}")
    col3.metric("Precision", f"{metrics.get('Precision', 0):.4f}")
    col4.metric("Concept Drifts", drift_count)
    
    # Visualizations
    st.markdown("---")
    v_col1, v_col2 = st.columns(2)
    
    # Chart 1: Performance Comparison
    perf_df = pd.DataFrame({
        "Metric": ["Accuracy", "F1", "Precision", "Recall"],
        "Value": [
            metrics.get("Accuracy", 0),
            metrics.get("F1", 0),
            metrics.get("Precision", 0),
            metrics.get("Recall", 0)
        ]
    })
    fig_perf = px.bar(perf_df, x="Metric", y="Value", color="Metric", 
                     title="Live Performance Metrics", range_y=[0, 1])
    v_col1.plotly_chart(fig_perf, use_container_width=True, key="perf_chart")
    
    # Chart 2: Class Distribution
    dist_data = data.get("class_distribution", {})
    if dist_data:
        dist_df = pd.DataFrame({
            "Class": list(dist_data.keys()),
            "Count": list(dist_data.values())
        }).sort_values(by="Count", ascending=False)
        
        fig_dist = px.bar(dist_df, x="Class", y="Count", color="Class",
                         title="Detection Type Distribution")
        v_col2.plotly_chart(fig_dist, use_container_width=True, key="dist_chart")
    
    # Detailed Report Row
    st.markdown("### Detailed Performance Report")
    st.table(perf_df)
else:
    st.warning("Waiting for data from the Multi-Agent System... Make sure main.py is running.")
    st.info("Ensure that 'data/metrics.json' is being generated by the SupervisorAgent.")

# Auto-refresh logic
time.sleep(refresh_rate)
st.rerun()
